version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "16:45"
      timezone: "Europe/London"
    groups:
      kotlin-core-plugins:
        patterns:
          - "org.jetbrains.kotlin.jvm"
          - "org.jetbrains.kotlin.plugin.serialization"
        update-types:
          - minor
          - patch
      gradle-minor-patch:
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "org.jetbrains.kotlin.jvm"
          - "org.jetbrains.kotlin.plugin.serialization"
